name: Metrics

# Controls when the workflow will run
on:
  schedule: [{cron: "0 0 * * *"}]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Terminal SVG
        uses: lowlighter/metrics@latest
        with:
          config_timezone: Europe/Helsinki
          template: terminal
          filename: terminal.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, metadata
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          config_order: base.header, base.metadata, isocalendar, languages
